name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore GoogleAnalyticsServiceForDotNet\GoogleAnalyticsServiceForDotNet.csproj
      working-directory: src
    - name: Build
      run: dotnet build GoogleAnalyticsServiceForDotNet --no-restore
      working-directory: src      
    - name: Test
      run: dotnet test GoogleAnalyticsServiceForDotNet.Tests --verbosity normal
      working-directory: src   
